attention_head_size: 64
attention_probs_dropout_prob: 0.1
hidden_act: gelu
hidden_dropout_prob: 0.1
hidden_size: 768
initializer_range: 0.02
intermediate_size: 3072
layer_norm_eps: 1.0e-07
max_position_embeddings: 0
max_relative_positions: 64
norm_rel_ebd: layer_norm
num_attention_heads: 12
num_hidden_layers: 12
pos_att_type: p2c|c2p
position_biased_input: false
position_buckets: 0
relative_attention: true
share_att_key: true
type_vocab_size: 0
vocab_size: 130505
